apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-mirror-config
data:
  docker: |
    DOCKER_OPTS="${DOCKER_OPTS} --data-root=/docker-graph"
    DOCKER_OPTS="${DOCKER_OPTS} --registry-mirror=http://docker-mirror.kubevirt-prow.svc:5000 --insecure-registry=http://docker-mirror.kubevirt-prow.svc:5000"
    DOCKER_OPTS="${DOCKER_OPTS} --mtu=1450"
