config_updater:
  maps:
    prow-config/config.yaml:
      name: config
    prow-config/jobs/**/*.yaml:
      name: job-config
    prow-config/plugins.yaml:
      name: plugins
    prow-config/labels.yaml:
      name: label-config

plugins:
  the-shadowmen:
  - size
  - label
  - hold
  - assign
  - blunderbuss
  - lifecycle
  - verify-owners
  - skip
  - override
  - wip
  - pony
  - dog
  - cat
  - approve

  the-shadowmen/prow-devconf:
  - trigger
  - owners-label
  - lgtm
  - config-updater

  the-shadowmen/kubevirtci:
  - trigger
  - owners-label
  - lgtm

  the-shadowmen/kubevirt-tutorial:
  - trigger
  - owners-label
  - lgtm

  the-shadowmen/kubevirt.github.io:
  - trigger
  - owners-label
  - lgtm

external_plugins:
  the-shadowmen:
  - name: needs-rebase
    events:
      - pull_request
  - name: cherrypicker

triggers:
- repos:
  - the-shadowmen/kubevirtci
- repos:
  - the-shadowmen/kubevirt-tutorial
- repos:
  - the-shadowmen/prow-devconf
- repos:
  - the-shadowmen/kubevirt.github.io

approve:
- repos:
  - the-shadowmen/kubevirt-tutorial
  - the-shadowmen/kubevirtci
  - the-shadowmen/prow-devconf
  - the-shadowmen/kubevirt.github.io
  implicit_self_approve: true
  lgtm_acts_as_approve: false

lgtm:
- repos:
  - the-shadowmen/kubevirt-tutorial
  - the-shadowmen/kubevirtci
  - the-shadowmen/prow-devconf
  - the-shadowmen/kubevirt.github.io
  review_acts_as_lgtm: true
