config_updater:
  maps:
    prow-config/config.yaml:
      name: config
      namespace: default
    prow-config/jobs/**/*.yaml:
      name: job-config
      namespace: default
    prow-config/plugins.yaml:
      name: plugins
      namespace: default
    prow-config/labels.yaml:
      name: label-config
      namespace: default

plugins:
  the-shadowmen:
  - size
  - label
  - hold
  - assign
  - blunderbuss
  - lifecycle
  - verify-owners
  - skip
  - override
  - wip
  - pony
  - dog
  - cat

  the-shadowmen/prow-devconf:
  - trigger
  - owners-label
  - lgtm
  - approve
  - config-updater

  the-shadowmen/kubevirtci:
  - trigger
  - owners-label
  - lgtm
  - approve

  the-shadowmen/kubevirt-tutorial:
  - trigger
  - owners-label
  - lgtm
  - approve

  the-shadowmen/kubevirt.github.io:
  - trigger
  - owners-label
  - lgtm
  - approve

external_plugins:
  the-shadowmen:
  - name: needs-rebase
    events:
      - pull_request
  - name: cherrypicker

triggers:
- repos:
  - the-shadowmen/kubevirtci
- repos:
  - the-shadowmen/kubevirt-tutorial
- repos:
  - the-shadowmen/prow-devconf
- repos:
  - the-shadowmen/kubevirt.github.io


approve:
- repos:
  - the-shadowmen/kubevirt-tutorial
  - the-shadowmen/kubevirtci
  - the-shadowmen/prow-devconf
  - the-shadowmen/kubevirt.github.io
  require_self_approval: true
  lgtm_acts_as_approve: false
  ignore_review_state: true

lgtm:
- repos:
  - the-shadowmen/kubevirt-tutorial
  - the-shadowmen/kubevirtci
  - the-shadowmen/prow-devconf
  - the-shadowmen/kubevirt.github.io
  review_acts_as_lgtm: true
