---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: label-sync
spec:
  schedule: "17 23 * * *"    # Every day 23:17 / 11:17PM
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: label-sync
    spec:
      template:
        spec:
          containers:
            - name: label-sync
              image: index.docker.io/kubevirtci/label_sync:v20181214-258f6ce10-dirty
              args:
              - --config=/etc/config/labels.yaml
              - --confirm=true
              - --orgs=the-shadowmen
              - --token=/etc/github/oauth
              volumeMounts:
              - name: oauth
                mountPath: /etc/github
                readOnly: true
              - name: config
                mountPath: /etc/config
                readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: oauth-token
          - name: config
            configMap:
              name: label-config
